#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActivityFavoriteButton

#include "Basic.hpp"

#include "ActivityFavoriteButton_classes.hpp"
#include "ActivityFavoriteButton_parameters.hpp"


namespace SDK
{

// Function ActivityFavoriteButton.ActivityFavoriteButton_C.ExecuteUbergraph_ActivityFavoriteButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityFavoriteButton_C::ExecuteUbergraph_ActivityFavoriteButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityFavoriteButton_C", "ExecuteUbergraph_ActivityFavoriteButton");

	Params::ActivityFavoriteButton_C_ExecuteUbergraph_ActivityFavoriteButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityFavoriteButton.ActivityFavoriteButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityFavoriteButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityFavoriteButton_C", "PreConstruct");

	Params::ActivityFavoriteButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

