#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BGA_ButterCakeFruitPlant

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BGA_ButterCakeFruitPlant.BGA_ButterCakeFruitPlant_C
// 0x0050 (0x0CD8 - 0x0C88)
class ABGA_ButterCakeFruitPlant_C final : public ABuildingSMActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0C88(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UHierarchicalInstancedStaticMeshComponent* HierarchicalInstancedStaticMesh;                // 0x0C90(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFortAthenaTrackableAIObjectComponent*  FortAthenaTrackableAIObject;                       // 0x0C98(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class FName                                   LootTierGroupName;                                 // 0x0CA0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          hasLoot;                                           // 0x0CA8(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CA9[0x7];                                      // 0x0CA9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPawn*                              LastInteractingPawn;                               // 0x0CB0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   InteractionLabel;                                  // 0x0CB8(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class USoundBase*                             PickupSound;                                       // 0x0CD0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)

public:
	void BlueprintOnInteract(const class AFortPawn* InteractingPawn, const EInteractionBeingAttempted InteractionBeingAttempted);
	void ExecuteUbergraph_BGA_ButterCakeFruitPlant(int32 EntryPoint);
	void ForceSetMeshCollision();
	void GetItemToGrant(class UFortItemDefinition** Item_Definition, int32* Count);
	void GiveItemToInventory();
	bool HasOpenInventorySlot(class APawn* Target);
	void OnDeathPlayEffects(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AFortPawn* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void OnDeathServer(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void OnLoaded_73107C82470A66DB1848FA81472288CE(class UObject* Loaded);
	void OnRep_hasLoot();
	void OnRep_PickUpSound();
	void PlayPickUpAudio(class UFortWorldItemDefinition* Target);
	void ReceiveBeginPlay();
	void SpawnLoot();

	bool BlueprintCanInteract(const class AFortPawn* InteractingPawn, const EInteractionBeingAttempted InteractionBeingAttempted, const ETInteractionType InteractionType) const;
	class FText BlueprintGetInteractionString(const class AFortPawn* InteractingPawn, const EInteractionBeingAttempted InteractionBeingAttempted) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BGA_ButterCakeFruitPlant_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BGA_ButterCakeFruitPlant_C")
	}
	static class ABGA_ButterCakeFruitPlant_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABGA_ButterCakeFruitPlant_C>();
	}
};
DUMPER7_ASSERTS_ABGA_ButterCakeFruitPlant_C;

}

