#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DynamicAthenaHudComponent

#include "Basic.hpp"

#include "DynamicAthenaHUD_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DynamicAthenaHudComponent.BP_DynamicAthenaHudComponent_C
// 0x0000 (0x00D0 - 0x00D0)
class UBP_DynamicAthenaHudComponent_C final : public UDynamicAthenaHudComponent
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DynamicAthenaHudComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DynamicAthenaHudComponent_C")
	}
	static class UBP_DynamicAthenaHudComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DynamicAthenaHudComponent_C>();
	}
};
DUMPER7_ASSERTS_UBP_DynamicAthenaHudComponent_C;

}

