#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS19_BattlePassCustomizationGrid

#include "Basic.hpp"

#include "BPS19_BattlePassCustomizationGrid_classes.hpp"
#include "BPS19_BattlePassCustomizationGrid_parameters.hpp"


namespace SDK
{

// Function BPS19_BattlePassCustomizationGrid.BPS19_BattlePassCustomizationGrid_C.ExecuteUbergraph_BPS19_BattlePassCustomizationGrid
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPS19_BattlePassCustomizationGrid_C::ExecuteUbergraph_BPS19_BattlePassCustomizationGrid(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS19_BattlePassCustomizationGrid_C", "ExecuteUbergraph_BPS19_BattlePassCustomizationGrid");

	Params::BPS19_BattlePassCustomizationGrid_C_ExecuteUbergraph_BPS19_BattlePassCustomizationGrid Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPS19_BattlePassCustomizationGrid.BPS19_BattlePassCustomizationGrid_C.OnPageSelected
// (Event, Public, BlueprintEvent)

void UBPS19_BattlePassCustomizationGrid_C::OnPageSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS19_BattlePassCustomizationGrid_C", "OnPageSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPS19_BattlePassCustomizationGrid.BPS19_BattlePassCustomizationGrid_C.OnPageUnselected
// (Event, Public, BlueprintEvent)

void UBPS19_BattlePassCustomizationGrid_C::OnPageUnselected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS19_BattlePassCustomizationGrid_C", "OnPageUnselected");

	UObject::ProcessEvent(Func, nullptr);
}

}

