#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS19_BattlePassCustomizationGrid

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPS19_BattlePassCustomizationGrid.BPS19_BattlePassCustomizationGrid_C.ExecuteUbergraph_BPS19_BattlePassCustomizationGrid
// 0x0004 (0x0004 - 0x0000)
struct BPS19_BattlePassCustomizationGrid_C_ExecuteUbergraph_BPS19_BattlePassCustomizationGrid final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPS19_BattlePassCustomizationGrid_C_ExecuteUbergraph_BPS19_BattlePassCustomizationGrid;

}

