#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DiscoveryBrowserUI

#include "Basic.hpp"


namespace SDK
{

// Enum DiscoveryBrowserUI.EFortActivityBrowserTagType
// NumValues: 0x0007
enum class EFortActivityBrowserTagType : uint8
{
	Default                                  = 0,
	EpicOriginal                             = 1,
	SquadSize                                = 2,
	MaxPlayers                               = 3,
	XP                                       = 4,
	PurchaseRequired                         = 5,
	EFortActivityBrowserTagType_MAX          = 6,
};

// Enum DiscoveryBrowserUI.EActivityBrowserTileStyle
// NumValues: 0x0004
enum class EActivityBrowserTileStyle : uint8
{
	Default                                  = 0,
	Minimal                                  = 1,
	Detailed                                 = 2,
	EActivityBrowserTileStyle_MAX            = 3,
};

// ScriptStruct DiscoveryBrowserUI.CachedSurfaceData
// 0x0018 (0x0018 - 0x0000)
struct FCachedSurfaceData final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UFortCreativeDiscoveryActivityProvider*> CachedDataProviders;                       // 0x0008(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FCachedSurfaceData;

// ScriptStruct DiscoveryBrowserUI.FortActivityScaleFontData
// 0x0008 (0x0008 - 0x0000)
struct FFortActivityScaleFontData final
{
public:
	int32                                         CharacterCountStart;                               // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FontSize;                                          // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FFortActivityScaleFontData;

}

