#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DownloadPanel

#include "Basic.hpp"

#include "DownloadPanel_classes.hpp"
#include "DownloadPanel_parameters.hpp"


namespace SDK
{

// Function DownloadPanel.DownloadPanel_C.BndEvt__DownloadPanel_OkButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonLegacy*              Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDownloadPanel_C::BndEvt__DownloadPanel_OkButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature(class UCommonButtonLegacy* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DownloadPanel_C", "BndEvt__DownloadPanel_OkButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature");

	Params::DownloadPanel_C_BndEvt__DownloadPanel_OkButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DownloadPanel.DownloadPanel_C.BndEvt__IconTextButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonLegacy*              Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDownloadPanel_C::BndEvt__IconTextButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature(class UCommonButtonLegacy* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DownloadPanel_C", "BndEvt__IconTextButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature");

	Params::DownloadPanel_C_BndEvt__IconTextButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DownloadPanel.DownloadPanel_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UDownloadPanel_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DownloadPanel_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DownloadPanel.DownloadPanel_C.CancelPanel
// (Public, BlueprintCallable, BlueprintEvent)

void UDownloadPanel_C::CancelPanel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DownloadPanel_C", "CancelPanel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DownloadPanel.DownloadPanel_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UDownloadPanel_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DownloadPanel_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DownloadPanel.DownloadPanel_C.ExecuteUbergraph_DownloadPanel
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDownloadPanel_C::ExecuteUbergraph_DownloadPanel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DownloadPanel_C", "ExecuteUbergraph_DownloadPanel");

	Params::DownloadPanel_C_ExecuteUbergraph_DownloadPanel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DownloadPanel.DownloadPanel_C.LinkCodeFailedToResolve
// (BlueprintCallable, BlueprintEvent)

void UDownloadPanel_C::LinkCodeFailedToResolve()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DownloadPanel_C", "LinkCodeFailedToResolve");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DownloadPanel.DownloadPanel_C.LinkCodeResolved
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    LinkCode_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    ProjectID_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    Title_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UDownloadPanel_C::LinkCodeResolved(const class FString& LinkCode_0, const class FString& ProjectID_0, const class FString& Title_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DownloadPanel_C", "LinkCodeResolved");

	Params::DownloadPanel_C_LinkCodeResolved Parms{};

	Parms.LinkCode_0 = std::move(LinkCode_0);
	Parms.ProjectID_0 = std::move(ProjectID_0);
	Parms.Title_0 = std::move(Title_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function DownloadPanel.DownloadPanel_C.OnAnalogValueChanged
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FAnalogInputEvent&         InAnalogInputEvent                                     (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UDownloadPanel_C::OnAnalogValueChanged(const struct FGeometry& MyGeometry, const struct FAnalogInputEvent& InAnalogInputEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DownloadPanel_C", "OnAnalogValueChanged");

	Params::DownloadPanel_C_OnAnalogValueChanged Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InAnalogInputEvent = std::move(InAnalogInputEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function DownloadPanel.DownloadPanel_C.OnFocusLost
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UDownloadPanel_C::OnFocusLost(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DownloadPanel_C", "OnFocusLost");

	Params::DownloadPanel_C_OnFocusLost Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function DownloadPanel.DownloadPanel_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UDownloadPanel_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DownloadPanel_C", "OnFocusReceived");

	Params::DownloadPanel_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function DownloadPanel.DownloadPanel_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UDownloadPanel_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DownloadPanel_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DownloadPanel.DownloadPanel_C.OnLinkCodeModified
// (BlueprintCallable, BlueprintEvent)

void UDownloadPanel_C::OnLinkCodeModified()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DownloadPanel_C", "OnLinkCodeModified");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DownloadPanel.DownloadPanel_C.PreviewTextureLoaded
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2DDynamic*                PreviewTexture                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDownloadPanel_C::PreviewTextureLoaded(class UTexture2DDynamic* PreviewTexture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DownloadPanel_C", "PreviewTextureLoaded");

	Params::DownloadPanel_C_PreviewTextureLoaded Parms{};

	Parms.PreviewTexture = PreviewTexture;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DownloadPanel.DownloadPanel_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UDownloadPanel_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DownloadPanel_C", "BP_GetDesiredFocusTarget");

	Params::DownloadPanel_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

