#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DualBladeMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass DualBladeMenu.DualBladeMenu_C
// 0x0010 (0x03A8 - 0x0398)
class UDualBladeMenu_C final : public UFortDualBladeMenu
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0398(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UOverlay*                               Overlay_xp;                                        // 0x03A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_DualBladeMenu(int32 EntryPoint);
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DualBladeMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DualBladeMenu_C")
	}
	static class UDualBladeMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDualBladeMenu_C>();
	}
};
DUMPER7_ASSERTS_UDualBladeMenu_C;

}

