#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DynamicAthenaHUD

#include "Basic.hpp"

#include "DynamicAthenaHUD_classes.hpp"
#include "DynamicAthenaHUD_parameters.hpp"


namespace SDK
{

// Function DynamicAthenaHUD.DynamicAthenaHudComponent.HandleCreativeQuickbarEquippedChanged
// (Final, Native, Private)
// Parameters:
// bool                                    bIsQuickbarEquipped                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UDynamicAthenaHudComponent::HandleCreativeQuickbarEquippedChanged(bool bIsQuickbarEquipped)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DynamicAthenaHudComponent", "HandleCreativeQuickbarEquippedChanged");

	Params::DynamicAthenaHudComponent_HandleCreativeQuickbarEquippedChanged Parms{};

	Parms.bIsQuickbarEquipped = bIsQuickbarEquipped;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function DynamicAthenaHUD.DynamicAthenaHudComponent.HandleEnteringVehicle
// (Final, Native, Private)

void UDynamicAthenaHudComponent::HandleEnteringVehicle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DynamicAthenaHudComponent", "HandleEnteringVehicle");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function DynamicAthenaHUD.DynamicAthenaHudComponent.HandleExitingVehicle
// (Final, Native, Private)

void UDynamicAthenaHudComponent::HandleExitingVehicle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DynamicAthenaHudComponent", "HandleExitingVehicle");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

