#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DynamicAthenaHUD

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class DynamicAthenaHUD.DynamicAthenaHudComponent
// 0x0020 (0x00D0 - 0x00B0)
class UDynamicAthenaHudComponent : public UActorComponent
{
public:
	TArray<class UDynamicUIScene*>                DefaultScenes;                                     // 0x00B0(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	class UDynamicUIScene*                        VehicleHUDScene;                                   // 0x00C0(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UDynamicUIScene*                        CreativeQuickbarScene;                             // 0x00C8(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void HandleCreativeQuickbarEquippedChanged(bool bIsQuickbarEquipped);
	void HandleEnteringVehicle();
	void HandleExitingVehicle();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("DynamicAthenaHudComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DynamicAthenaHudComponent")
	}
	static class UDynamicAthenaHudComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDynamicAthenaHudComponent>();
	}
};
DUMPER7_ASSERTS_UDynamicAthenaHudComponent;

}

