#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_MED_Prime_PASIFIKA_FaceAcc_hair_Skeleton_AnimBlueprint

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass F_MED_Prime_PASIFIKA_FaceAcc_hair_Skeleton_AnimBlueprint.F_MED_Prime_PASIFIKA_FaceAcc_hair_Skeleton_AnimBlueprint_C
// 0x0B00 (0x1080 - 0x0580)
class UF_MED_Prime_PASIFIKA_FaceAcc_hair_Skeleton_AnimBlueprint_C final : public UCustomCharacterPartAnimInstance
{
public:
	uint8                                         Pad_578[0x8];                                      // 0x0578(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0580(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0588(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0590(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0598(0x0020)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh;                    // 0x05B8(0x0188)(ContainsInstancedReference)
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x0740(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x0760(0x0020)()
	struct FAnimNode_RigidBody                    AnimGraphNode_RigidBody;                           // 0x0780(0x07F0)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x0F70(0x0108)()
	float                                         Neck_Alpha;                                        // 0x1078(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void ExecuteUbergraph_F_MED_Prime_PASIFIKA_FaceAcc_hair_Skeleton_AnimBlueprint(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("F_MED_Prime_PASIFIKA_FaceAcc_hair_Skeleton_AnimBlueprint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"F_MED_Prime_PASIFIKA_FaceAcc_hair_Skeleton_AnimBlueprint_C")
	}
	static class UF_MED_Prime_PASIFIKA_FaceAcc_hair_Skeleton_AnimBlueprint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_MED_Prime_PASIFIKA_FaceAcc_hair_Skeleton_AnimBlueprint_C>();
	}
};
DUMPER7_ASSERTS_UF_MED_Prime_PASIFIKA_FaceAcc_hair_Skeleton_AnimBlueprint_C;

}

