#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNL_Athena_MultiInteract

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCNL_Athena_MultiInteract.GCNL_Athena_MultiInteract_C
// 0x0078 (0x0880 - 0x0808)
class AGCNL_Athena_MultiInteract_C final : public AFortGameplayCueNotify_Loop
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0808(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAudioComponent*                        Audio;                                             // 0x0810(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         CurrentPitch;                                      // 0x0818(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TargetPitch;                                       // 0x081C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMap<int32, float>                            Pitch_Map;                                         // 0x0820(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         PreviousPitch;                                     // 0x0870(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_874[0x4];                                      // 0x0874(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           TargetProgressHandle;                              // 0x0878(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void CheckTargetProgress();
	void ExecuteUbergraph_GCNL_Athena_MultiInteract(int32 EntryPoint);
	void OnApplicationGeneric(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UFXSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UMatineeCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance);
	void OnLoopingStartGeneric(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UFXSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents);
	void OnRemovalGeneric(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UFXSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UMatineeCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance);
	void SetPitchBasedOnPlayerCount(int32 InteractingPlayerCount, float MultiInteractMultiplier, float InteractingDuration);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCNL_Athena_MultiInteract_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCNL_Athena_MultiInteract_C")
	}
	static class AGCNL_Athena_MultiInteract_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCNL_Athena_MultiInteract_C>();
	}
};
DUMPER7_ASSERTS_AGCNL_Athena_MultiInteract_C;

}

