#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Hotfix_BuildingPropWithLootComp_Parent

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Hotfix_BuildingPropWithLootComp_Parent.Hotfix_BuildingPropWithLootComp_Parent_C
// 0x0088 (0x0E20 - 0x0D98)
class AHotfix_BuildingPropWithLootComp_Parent_C : public ABuildingProp
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0D98(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBuildingActorLootDropOnDeathComponent_C* BuildingActorLootDropOnDeathComponent;           // 0x0DA0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         Row_ActorEnabled;                                  // 0x0DA8(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         Row_InteractEnabled;                               // 0x0DD0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UParticleSystem*                        FX_Open;                                           // 0x0DF8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                FX_OpenOffsetLocation;                             // 0x0E00(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FX_OpenPitchOffset;                                // 0x0E0C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Sound_Open;                                        // 0x0E10(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DisableLootOnDisableInteract;                      // 0x0E18(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Hotfix_BuildingPropWithLootComp_Parent(int32 EntryPoint);
	void OnLoot_1();
	void OnReady_66411D114A9FDC07FF39F89B35B7E7AB(class AFortGameStateAthena* GameState, const class UFortPlaylist* Playlist, const struct FGameplayTagContainer& PlaylistContextTags);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Hotfix_BuildingPropWithLootComp_Parent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Hotfix_BuildingPropWithLootComp_Parent_C")
	}
	static class AHotfix_BuildingPropWithLootComp_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHotfix_BuildingPropWithLootComp_Parent_C>();
	}
};
DUMPER7_ASSERTS_AHotfix_BuildingPropWithLootComp_Parent_C;

}

