#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KoalaRuntime

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// Class KoalaRuntime.FortContextualTutorial_GameplayEventKoala
// 0x0000 (0x0170 - 0x0170)
class UFortContextualTutorial_GameplayEventKoala final : public UFortContextualTutorial_GameplayEvent
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FortContextualTutorial_GameplayEventKoala")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FortContextualTutorial_GameplayEventKoala")
	}
	static class UFortContextualTutorial_GameplayEventKoala* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortContextualTutorial_GameplayEventKoala>();
	}
};
DUMPER7_ASSERTS_UFortContextualTutorial_GameplayEventKoala;

}

