#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KoalaUI

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "KoalaUI_structs.hpp"
#include "CommonUI_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// Class KoalaUI.FortGameSettingRegistryExtension_Koala
// 0x0030 (0x0058 - 0x0028)
class UFortGameSettingRegistryExtension_Koala final : public UFortGameSettingRegistryExtension
{
public:
	struct FFortSettingNameExtensions             SettingExtensions;                                 // 0x0028(0x0018)(Edit, NativeAccessSpecifierPrivate)
	uint8                                         Pad_40[0x18];                                      // 0x0040(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FortGameSettingRegistryExtension_Koala")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FortGameSettingRegistryExtension_Koala")
	}
	static class UFortGameSettingRegistryExtension_Koala* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortGameSettingRegistryExtension_Koala>();
	}
};
DUMPER7_ASSERTS_UFortGameSettingRegistryExtension_Koala;

// Class KoalaUI.FortSidebarPanelKoala
// 0x0028 (0x0358 - 0x0330)
class UFortSidebarPanelKoala : public UCommonActivatableWidget
{
public:
	uint8                                         Pad_330[0x8];                                      // 0x0330(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      Button_KoalaDummy;                                 // 0x0338(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UFortLazyImage*                         QrCodeImage;                                       // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class FString                                 QRCodeURL;                                         // 0x0348(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FortSidebarPanelKoala")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FortSidebarPanelKoala")
	}
	static class UFortSidebarPanelKoala* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortSidebarPanelKoala>();
	}
};
DUMPER7_ASSERTS_UFortSidebarPanelKoala;

// Class KoalaUI.KoalaHUDWidget
// 0x00C0 (0x03F0 - 0x0330)
class UKoalaHUDWidget final : public UCommonActivatableWidget
{
public:
	float                                         ClipDebounceTime;                                  // 0x0330(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         PlayerKilledPlayerReminderTime;                    // 0x0334(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         MatchEndedReminderTime;                            // 0x0338(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         ClipReminderCooldownTime;                          // 0x033C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class USoundSubmix*                           ClipAudioSubmix;                                   // 0x0340(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonActionWidget*                    ClipActionWidget;                                  // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FDataTableRowHandle                    ClipObjectInputAction;                             // 0x0350(0x0010)(Edit, NoDestructor, NativeAccessSpecifierPrivate)
	uint8                                         Pad_360[0x8];                                      // 0x0360(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<int32, struct FKoalaClipInfo>            ClipTracker;                                       // 0x0368(0x0050)(NativeAccessSpecifierPrivate)
	uint8                                         Pad_3B8[0x8];                                      // 0x03B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LastClipID;                                        // 0x03C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_3C4[0x14];                                     // 0x03C4(0x0014)(Fixing Size After Last Property [ Dumper-7 ])
	EKoalaMockClipMode                            MockClipMode;                                      // 0x03D8(0x0001)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_3D9[0x3];                                      // 0x03D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         MockClipUploadShortTime;                           // 0x03DC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         MockClipUploadLongTime;                            // 0x03E0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         MockClipCreateShortTime;                           // 0x03E4(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         MockClipCreateLongTime;                            // 0x03E8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_3EC[0x4];                                      // 0x03EC(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	int32 GetTrackedClipCount();
	void OnAvailabilityChanged(EKoalaAvailability Availability);
	void OnClipStatusChanged(int32 InClipID, EKoalaClipStatus InClipStatus, float InUploadProgress);
	void OnConnectionChanged(EKoalaConnectionStatus InStatus);
	void OnCreateClipComplete(bool bSuccess);
	void OnInputComplete();
	void OnInputProgress(float Progress);
	void OnRecordingStatusChanged(EKoalaRecording InRecordingStatus);
	void OnReminderEnded();
	void OnReminderTimerStarted(float Time);
	void RegisterClipButtonInput();
	void UnregisterClipButtonInput();

	int32 GetUploadingClipCount() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KoalaHUDWidget")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KoalaHUDWidget")
	}
	static class UKoalaHUDWidget* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKoalaHUDWidget>();
	}
};
DUMPER7_ASSERTS_UKoalaHUDWidget;

// Class KoalaUI.KoalaMainMenuButton
// 0x0000 (0x1010 - 0x1010)
class UKoalaMainMenuButton : public UFortMainMenuButtonExtension
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KoalaMainMenuButton")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KoalaMainMenuButton")
	}
	static class UKoalaMainMenuButton* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKoalaMainMenuButton>();
	}
};
DUMPER7_ASSERTS_UKoalaMainMenuButton;

// Class KoalaUI.KoalaSettingDetailExtension
// 0x0000 (0x0250 - 0x0250)
class UKoalaSettingDetailExtension final : public UFortSettingDetailExtension
{
public:
	void OnAvailabilityChanged(bool bAvailable);
	void OnConnectionChanged(bool bConnected);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KoalaSettingDetailExtension")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KoalaSettingDetailExtension")
	}
	static class UKoalaSettingDetailExtension* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKoalaSettingDetailExtension>();
	}
};
DUMPER7_ASSERTS_UKoalaSettingDetailExtension;

}

