#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PriceChangeAcknowledgeModal

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"


namespace SDK::Params
{

// Function PriceChangeAcknowledgeModal.PriceChangeAcknowledgeModal_C.BndEvt__PriceChangeAcknowledgeModal_BP_PriceChangeAcknowledgeCheckBox_K2Node_ComponentBoundEvent_0_CommonSelectedStateChangedBase__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct PriceChangeAcknowledgeModal_C_BndEvt__PriceChangeAcknowledgeModal_BP_PriceChangeAcknowledgeCheckBox_K2Node_ComponentBoundEvent_0_CommonSelectedStateChangedBase__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Selected;                                          // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PriceChangeAcknowledgeModal_C_BndEvt__PriceChangeAcknowledgeModal_BP_PriceChangeAcknowledgeCheckBox_K2Node_ComponentBoundEvent_0_CommonSelectedStateChangedBase__DelegateSignature;

// Function PriceChangeAcknowledgeModal.PriceChangeAcknowledgeModal_C.ExecuteUbergraph_PriceChangeAcknowledgeModal
// 0x0208 (0x0208 - 0x0000)
struct PriceChangeAcknowledgeModal_C_ExecuteUbergraph_PriceChangeAcknowledgeModal final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class URichTextButton_C*                      K2Node_DynamicCast_AsRich_Text_Button;             // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0018(0x0018)()
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable_1;                              // 0x0038(0x0018)()
	class USubscriptionModalButton_C*             K2Node_DynamicCast_AsSubscription_Modal_Button;    // 0x0050(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USubscriptionModalButton_C*             K2Node_DynamicCast_AsSubscription_Modal_Button_1;  // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_69[0x3];                                       // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_Event_Title;                                // 0x0070(0x0018)(ConstParm)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Event_BodyText;                             // 0x0090(0x0018)(ConstParm)
	class FText                                   K2Node_Event_CheckboxText;                         // 0x00A8(0x0018)(ConstParm)
	class FText                                   K2Node_Event_ConfirmButtonText_1;                  // 0x00C0(0x0018)(ConstParm)
	class FText                                   K2Node_Event_CancelSubscriptionButtonText;         // 0x00D8(0x0018)(ConstParm)
	class FText                                   K2Node_Event_MoreInfoUrl;                          // 0x00F0(0x0018)(ConstParm)
	class FText                                   K2Node_Event_ConfirmButtonText;                    // 0x0108(0x0018)(ConstParm)
	TArray<struct FCrewTableRow>                  K2Node_Event_PriceChangeByRegionRows;              // 0x0120(0x0010)(ConstParm, ReferenceParm)
	struct FCrewTableRow                          CallFunc_Array_Get_Item;                           // 0x0130(0x0018)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0148(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x014C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x014D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue_1;         // 0x014E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14F[0x1];                                      // 0x014F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default;                             // 0x0150(0x0018)()
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue_2;         // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsEmpty_ReturnValue;                // 0x0169(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x016A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x016B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16C[0x4];                                      // 0x016C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default_1;                           // 0x0170(0x0018)()
	class UUserWidget*                            CallFunc_BP_CreateEntry_ReturnValue;               // 0x0188(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPriceChangeRegionListEntry_C*          K2Node_DynamicCast_AsPrice_Change_Region_List_Entry; // 0x0190(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_199[0x7];                                      // 0x0199(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue_1;       // 0x01A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable_2;                              // 0x01B0(0x0018)()
	bool                                          Temp_bool_Variable_2;                              // 0x01C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C9[0x7];                                      // 0x01C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default_2;                           // 0x01D0(0x0018)()
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button;                 // 0x01E8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_Selected;               // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1F1[0x3];                                      // 0x01F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x01F4(0x0010)(ZeroConstructor, NoDestructor)
};
DUMPER7_ASSERTS_PriceChangeAcknowledgeModal_C_ExecuteUbergraph_PriceChangeAcknowledgeModal;

// Function PriceChangeAcknowledgeModal.PriceChangeAcknowledgeModal_C.OnSetPriceChangeAcknowledgeBodyTable
// 0x0010 (0x0010 - 0x0000)
struct PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeBodyTable final
{
public:
	TArray<struct FCrewTableRow>                  PriceChangeByRegionRows;                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeBodyTable;

// Function PriceChangeAcknowledgeModal.PriceChangeAcknowledgeModal_C.OnSetPriceChangeAcknowledgeBodyText
// 0x0018 (0x0018 - 0x0000)
struct PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeBodyText final
{
public:
	class FText                                   BodyText;                                          // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeBodyText;

// Function PriceChangeAcknowledgeModal.PriceChangeAcknowledgeModal_C.OnSetPriceChangeAcknowledgeCancelSubscriptionButtonText
// 0x0018 (0x0018 - 0x0000)
struct PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeCancelSubscriptionButtonText final
{
public:
	class FText                                   CancelSubscriptionButtonText;                      // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeCancelSubscriptionButtonText;

// Function PriceChangeAcknowledgeModal.PriceChangeAcknowledgeModal_C.OnSetPriceChangeAcknowledgeCheckboxText
// 0x0018 (0x0018 - 0x0000)
struct PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeCheckboxText final
{
public:
	class FText                                   CheckboxText;                                      // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeCheckboxText;

// Function PriceChangeAcknowledgeModal.PriceChangeAcknowledgeModal_C.OnSetPriceChangeAcknowledgeConfirmButtonText
// 0x0018 (0x0018 - 0x0000)
struct PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeConfirmButtonText final
{
public:
	class FText                                   ConfirmButtonText;                                 // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeConfirmButtonText;

// Function PriceChangeAcknowledgeModal.PriceChangeAcknowledgeModal_C.OnSetPriceChangeAcknowledgeMoreInfoText
// 0x0018 (0x0018 - 0x0000)
struct PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeMoreInfoText final
{
public:
	class FText                                   ConfirmButtonText;                                 // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeMoreInfoText;

// Function PriceChangeAcknowledgeModal.PriceChangeAcknowledgeModal_C.OnSetPriceChangeAcknowledgeMoreInfoUrl
// 0x0018 (0x0018 - 0x0000)
struct PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeMoreInfoUrl final
{
public:
	class FText                                   MoreInfoUrl;                                       // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeMoreInfoUrl;

// Function PriceChangeAcknowledgeModal.PriceChangeAcknowledgeModal_C.OnSetPriceChangeAcknowledgeTitle
// 0x0018 (0x0018 - 0x0000)
struct PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeTitle final
{
public:
	class FText                                   Title;                                             // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_PriceChangeAcknowledgeModal_C_OnSetPriceChangeAcknowledgeTitle;

}

