#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PriceChangeAcknowledgeTextEntry

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PriceChangeAcknowledgeTextEntry.PriceChangeAcknowledgeTextEntry_C
// 0x0028 (0x0270 - 0x0248)
class UPriceChangeAcknowledgeTextEntry_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0248(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonRichTextBlock*                   Description;                                       // 0x0250(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   Text;                                              // 0x0258(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)

public:
	void Construct();
	void ExecuteUbergraph_PriceChangeAcknowledgeTextEntry(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetText(const class FText& InText);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PriceChangeAcknowledgeTextEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PriceChangeAcknowledgeTextEntry_C")
	}
	static class UPriceChangeAcknowledgeTextEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPriceChangeAcknowledgeTextEntry_C>();
	}
};
DUMPER7_ASSERTS_UPriceChangeAcknowledgeTextEntry_C;

}

