#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PriceChangeAcknowledgeModal

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CrewUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PriceChangeAcknowledgeModal.PriceChangeAcknowledgeModal_C
// 0x00A0 (0x0570 - 0x04D0)
class UPriceChangeAcknowledgeModal_C final : public UCrewPriceChangeAcknowledgeModal
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Dismiss;                                           // 0x04D8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       ShowUp;                                            // 0x04E0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UPriceChangeAcknowledgeTextEntry_C*     BodyText_1;                                        // 0x04E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_Material_1;                                 // 0x04F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PriceChangeAcknowledgeCheckBox_C*   BP_PriceChangeAcknowledgeCheckBox;                 // 0x04F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   Column1Header;                                     // 0x0500(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   Column2Header;                                     // 0x0508(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   Column3Header;                                     // 0x0510(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USafeZone*                              ContentSZ;                                         // 0x0518(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDynamicEntryBox*                       EntryBox_PriceChangeTable;                         // 0x0520(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaScrollBox*                       ScrollBox_PriceChangeTable;                        // 0x0528(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_Height_1;                                  // 0x0530(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBoxHeader;                                     // 0x0538(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   Text_Check;                                        // 0x0540(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   Text_MoreInfo;                                     // 0x0548(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Title;                                        // 0x0550(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   Disabled_Reason;                                   // 0x0558(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void BndEvt__PriceChangeAcknowledgeModal_BP_PriceChangeAcknowledgeCheckBox_K2Node_ComponentBoundEvent_0_CommonSelectedStateChangedBase__DelegateSignature(class UCommonButtonBase* Button, bool Selected);
	void BP_OnActivated();
	void ExecuteUbergraph_PriceChangeAcknowledgeModal(int32 EntryPoint);
	void On_Exit_Modal();
	void OnModalBackout();
	void OnSetPriceChangeAcknowledgeBodyTable(const TArray<struct FCrewTableRow>& PriceChangeByRegionRows);
	void OnSetPriceChangeAcknowledgeBodyText(const class FText& BodyText);
	void OnSetPriceChangeAcknowledgeCancelSubscriptionButtonText(const class FText& CancelSubscriptionButtonText);
	void OnSetPriceChangeAcknowledgeCheckboxText(const class FText& CheckboxText);
	void OnSetPriceChangeAcknowledgeConfirmButtonText(const class FText& ConfirmButtonText);
	void OnSetPriceChangeAcknowledgeMoreInfoText(const class FText& ConfirmButtonText);
	void OnSetPriceChangeAcknowledgeMoreInfoUrl(const class FText& MoreInfoUrl);
	void OnSetPriceChangeAcknowledgeTitle(const class FText& Title);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PriceChangeAcknowledgeModal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PriceChangeAcknowledgeModal_C")
	}
	static class UPriceChangeAcknowledgeModal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPriceChangeAcknowledgeModal_C>();
	}
};
DUMPER7_ASSERTS_UPriceChangeAcknowledgeModal_C;

}

