#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RichLightningViolator

#include "Basic.hpp"

#include "RichLightningViolator_classes.hpp"
#include "RichLightningViolator_parameters.hpp"


namespace SDK
{

// Function RichLightningViolator.RichLightningViolator_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void URichLightningViolator_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RichLightningViolator_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RichLightningViolator.RichLightningViolator_C.EventBorderSize
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   BorderSize                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URichLightningViolator_C::EventBorderSize(float BorderSize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RichLightningViolator_C", "EventBorderSize");

	Params::RichLightningViolator_C_EventBorderSize Parms{};

	Parms.BorderSize = BorderSize;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RichLightningViolator.RichLightningViolator_C.EventColorBG
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLinearColor&              NewColor                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URichLightningViolator_C::EventColorBG(const struct FLinearColor& NewColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RichLightningViolator_C", "EventColorBG");

	Params::RichLightningViolator_C_EventColorBG Parms{};

	Parms.NewColor = std::move(NewColor);

	UObject::ProcessEvent(Func, &Parms);
}


// Function RichLightningViolator.RichLightningViolator_C.EventColorBorder
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLinearColor&              NewColor                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URichLightningViolator_C::EventColorBorder(const struct FLinearColor& NewColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RichLightningViolator_C", "EventColorBorder");

	Params::RichLightningViolator_C_EventColorBorder Parms{};

	Parms.NewColor = std::move(NewColor);

	UObject::ProcessEvent(Func, &Parms);
}


// Function RichLightningViolator.RichLightningViolator_C.EventSetText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      NewText                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void URichLightningViolator_C::EventSetText(const class FText& NewText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RichLightningViolator_C", "EventSetText");

	Params::RichLightningViolator_C_EventSetText Parms{};

	Parms.NewText = std::move(NewText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function RichLightningViolator.RichLightningViolator_C.ExecuteUbergraph_RichLightningViolator
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URichLightningViolator_C::ExecuteUbergraph_RichLightningViolator(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RichLightningViolator_C", "ExecuteUbergraph_RichLightningViolator");

	Params::RichLightningViolator_C_ExecuteUbergraph_RichLightningViolator Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RichLightningViolator.RichLightningViolator_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URichLightningViolator_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RichLightningViolator_C", "PreConstruct");

	Params::RichLightningViolator_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RichLightningViolator.RichLightningViolator_C.TailPosition
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ShowTail                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EHorizontalAlignment                    HPosition                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EVerticalAlignment                      VPosition                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EPlaneDirection                         TailDirection_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URichLightningViolator_C::TailPosition(bool ShowTail, EHorizontalAlignment HPosition, EVerticalAlignment VPosition, EPlaneDirection TailDirection_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RichLightningViolator_C", "TailPosition");

	Params::RichLightningViolator_C_TailPosition Parms{};

	Parms.ShowTail = ShowTail;
	Parms.HPosition = HPosition;
	Parms.VPosition = VPosition;
	Parms.TailDirection_0 = TailDirection_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

