#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SentryRuntime

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// Class SentryRuntime.CreativeSentryAnimInstance
// 0x0020 (0x04F0 - 0x04D0)
class UCreativeSentryAnimInstance final : public UFortDefenderAnimInstance
{
public:
	float                                         RotateAimAnimationPitch;                           // 0x04C8(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CounterRotateAimAnimationPitch;                    // 0x04CC(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsRelaxedLevel1OrNotTargeting;                    // 0x04D0(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4D1[0x3];                                      // 0x04D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         RightHandIKAlpha;                                  // 0x04D4(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OneMinusLeftHandFK;                                // 0x04D8(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LeftHandIKAlpha;                                   // 0x04DC(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RetargetHandIKBonesToFKPositionWeight;             // 0x04E0(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4E4[0xC];                                      // 0x04E4(0x000C)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CreativeSentryAnimInstance")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CreativeSentryAnimInstance")
	}
	static class UCreativeSentryAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCreativeSentryAnimInstance>();
	}
};
DUMPER7_ASSERTS_UCreativeSentryAnimInstance;

}

