#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Sidebar

#include "Basic.hpp"


namespace SDK::Params
{

// Function Sidebar.Sidebar_C.ExecuteUbergraph_Sidebar
// 0x0004 (0x0004 - 0x0000)
struct Sidebar_C_ExecuteUbergraph_Sidebar final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Sidebar_C_ExecuteUbergraph_Sidebar;

}

