#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SidebarPanelKoala

#include "Basic.hpp"


namespace SDK::Params
{

// Function SidebarPanelKoala.SidebarPanelKoala_C.ExecuteUbergraph_SidebarPanelKoala
// 0x0008 (0x0008 - 0x0000)
struct SidebarPanelKoala_C_ExecuteUbergraph_SidebarPanelKoala final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetConsoleVariableBoolValue_ReturnValue;  // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SidebarPanelKoala_C_ExecuteUbergraph_SidebarPanelKoala;

}

