#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SidebarPanelKoala

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "KoalaUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SidebarPanelKoala.SidebarPanelKoala_C
// 0x0018 (0x0370 - 0x0358)
class USidebarPanelKoala_C final : public UFortSidebarPanelKoala
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0358(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UVerticalBox*                           PanelWidget_KoalaElements;                         // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   Text_KoalaDescription;                             // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_SidebarPanelKoala(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SidebarPanelKoala_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SidebarPanelKoala_C")
	}
	static class USidebarPanelKoala_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USidebarPanelKoala_C>();
	}
};
DUMPER7_ASSERTS_USidebarPanelKoala_C;

}

