#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Sidebar

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Sidebar.Sidebar_C
// 0x0080 (0x0518 - 0x0498)
class USidebar_C final : public UFortSocialPanelView_Sidebar
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0498(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USidebarProfile_C*                      Panel_Profile;                                     // 0x04A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USafeZone*                              Safezone_OnboardingTooltip;                        // 0x04A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USafeZone*                              SafeZone_SideBar;                                  // 0x04B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   Text_PartyUp;                                      // 0x04B8(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   Text_FindFriends;                                  // 0x04D0(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   Text_VoiceChat;                                    // 0x04E8(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   Text_UserSettings;                                 // 0x0500(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void BP_OnActivated();
	void ExecuteUbergraph_Sidebar(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Sidebar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Sidebar_C")
	}
	static class USidebar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USidebar_C>();
	}
};
DUMPER7_ASSERTS_USidebar_C;

}

