#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SlidingLayerAnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function SlidingLayerAnimBP.SlidingLayerAnimBP_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct SlidingLayerAnimBP_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_SlidingLayerAnimBP_C_AnimGraph;

// Function SlidingLayerAnimBP.SlidingLayerAnimBP_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct SlidingLayerAnimBP_C_BlueprintUpdateAnimation final
{
public:
	float                                         DeltaTimeX;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SlidingLayerAnimBP_C_BlueprintUpdateAnimation;

// Function SlidingLayerAnimBP.SlidingLayerAnimBP_C.ExecuteUbergraph_SlidingLayerAnimBP
// 0x0008 (0x0008 - 0x0000)
struct SlidingLayerAnimBP_C_ExecuteUbergraph_SlidingLayerAnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaTimeX;                           // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SlidingLayerAnimBP_C_ExecuteUbergraph_SlidingLayerAnimBP;

// Function SlidingLayerAnimBP.SlidingLayerAnimBP_C.MovementMode_LocomotionUpperBodyAdditive
// 0x0030 (0x0030 - 0x0000)
struct SlidingLayerAnimBP_C_MovementMode_LocomotionUpperBodyAdditive final
{
public:
	struct FPoseLink                              InPose_0;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              IdleAdditive_CachedPose;                           // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              MovementMode_LocomotionUpperBodyAdditive_0;        // 0x0020(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_SlidingLayerAnimBP_C_MovementMode_LocomotionUpperBodyAdditive;

// Function SlidingLayerAnimBP.SlidingLayerAnimBP_C.MovementMode_LowerBodyOverride
// 0x0020 (0x0020 - 0x0000)
struct SlidingLayerAnimBP_C_MovementMode_LowerBodyOverride final
{
public:
	struct FPoseLink                              InPose;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              MovementMode_LowerBodyOverride_0;                  // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_SlidingLayerAnimBP_C_MovementMode_LowerBodyOverride;

// Function SlidingLayerAnimBP.SlidingLayerAnimBP_C.MovementMode_UpperBodyPose
// 0x0030 (0x0030 - 0x0000)
struct SlidingLayerAnimBP_C_MovementMode_UpperBodyPose final
{
public:
	struct FPoseLink                              UppperBodyPose_BasePose;                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              UpperBodyPose_AdditiveIdentityPose;                // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              MovementMode_UpperBodyPose_0;                      // 0x0020(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_SlidingLayerAnimBP_C_MovementMode_UpperBodyPose;

}

