#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpecialEventGameplayUI

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function SpecialEventGameplayUI.SpecialEventCursorWidget.OnDesiredVisibilityChanged
// 0x0010 (0x0010 - 0x0000)
struct SpecialEventCursorWidget_OnDesiredVisibilityChanged final
{
public:
	class USpecialEventCursorComponent*           InCursorComponent;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bShouldBeVisible;                                  // 0x0008(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SpecialEventCursorWidget_OnDesiredVisibilityChanged;

// Function SpecialEventGameplayUI.SpecialEventCursorWidget.OnLocationChanged
// 0x0018 (0x0018 - 0x0000)
struct SpecialEventCursorWidget_OnLocationChanged final
{
public:
	class USpecialEventCursorComponent*           InCursorComponent;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              NormalizedLocation;                                // 0x0008(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FIntPoint                              ViewportLocation;                                  // 0x0010(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SpecialEventCursorWidget_OnLocationChanged;

// Function SpecialEventGameplayUI.SpecialEventUILibrary.HideFrontEndStateWidget
// 0x0010 (0x0010 - 0x0000)
struct SpecialEventUILibrary_HideFrontEndStateWidget final
{
public:
	const class UObject*                          WorldContextObject;                                // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bNewlyHidden;                                      // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SpecialEventUILibrary_HideFrontEndStateWidget;

}

