#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SuperstormRuntime

#include "Basic.hpp"

#include "SuperstormRuntime_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "FieldSystemEngine_classes.hpp"
#include "ModularGameplay_classes.hpp"
#include "TargetingSystem_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// Class SuperstormRuntime.TempestLightningComponent
// 0x0388 (0x0438 - 0x00B0)
class UTempestLightningComponent final : public UGameFrameworkComponent
{
public:
	TSubclassOf<class AFortGameplayEffectDeliveryActor> LightningBoltClass;                          // 0x00B0(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<struct FTempestLightningBoltEffectContainer> LightningBoltTargetEffectContainers;         // 0x00B8(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPrivate)
	class UTargetingPreset*                       LightningBoltTargetingPreset;                      // 0x00C8(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UEnvQuery*                              FindTargetablePawnsQuery;                          // 0x00D0(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UEnvQuery*                              FindTargetableLocationQuery;                       // 0x00D8(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class FName                                   EnvironmentQueryParamName_LightningRadius;         // 0x00E0(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class FName                                   EnvironmentQueryParamName_MinLightningTargetDistance; // 0x00E8(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FScalableFloat                         LightningCloudHeight;                              // 0x00F0(0x0028)(Edit, NativeAccessSpecifierPrivate)
	struct FScalableFloat                         LightningRadius;                                   // 0x0118(0x0028)(Edit, NativeAccessSpecifierPrivate)
	struct FScalableFloat                         MinLightningTargetDistance;                        // 0x0140(0x0028)(Edit, NativeAccessSpecifierPrivate)
	struct FScalableFloat                         LightningFrequencyMin;                             // 0x0168(0x0028)(Edit, NativeAccessSpecifierPrivate)
	struct FScalableFloat                         LightningFrequencyMax;                             // 0x0190(0x0028)(Edit, NativeAccessSpecifierPrivate)
	struct FScalableFloat                         LightningBoltsMin;                                 // 0x01B8(0x0028)(Edit, NativeAccessSpecifierPrivate)
	struct FScalableFloat                         LightningBoltsMax;                                 // 0x01E0(0x0028)(Edit, NativeAccessSpecifierPrivate)
	struct FScalableFloat                         LightningBoltIntervalMin;                          // 0x0208(0x0028)(Edit, NativeAccessSpecifierPrivate)
	struct FScalableFloat                         LightningBoltIntervalMax;                          // 0x0230(0x0028)(Edit, NativeAccessSpecifierPrivate)
	struct FScalableFloat                         LightningBoltSeparationDistance;                   // 0x0258(0x0028)(Edit, NativeAccessSpecifierPrivate)
	struct FScalableFloat                         LightningStruckPawnReselectionInterval;            // 0x0280(0x0028)(Edit, NativeAccessSpecifierPrivate)
	struct FScalableFloat                         LightningBoltTelegraphDuration;                    // 0x02A8(0x0028)(Edit, NativeAccessSpecifierPrivate)
	struct FScalableFloat                         LightningBoltImpactIgnitionRadius;                 // 0x02D0(0x0028)(Edit, NativeAccessSpecifierPrivate)
	struct FScalableFloat                         LightningBoltGrassIgnitionRadius;                  // 0x02F8(0x0028)(Edit, NativeAccessSpecifierPrivate)
	struct FScalableFloat                         LightningBoltGrassFirePropagationFuel;             // 0x0320(0x0028)(Edit, NativeAccessSpecifierPrivate)
	struct FGameplayTag                           LightningAreaTargetTelegraphCue;                   // 0x0348(0x0008)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FGameplayTag                           LightningBoltTargetTelegraphCue;                   // 0x0350(0x0008)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<struct FTempestLightningBoltData>      LightningBoltData;                                 // 0x0358(0x0010)(ZeroConstructor, Transient, NativeAccessSpecifierPrivate)
	uint8                                         Pad_368[0xD0];                                     // 0x0368(0x00D0)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	float GetCloudHeight() const;
	float GetLightningRadius() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TempestLightningComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TempestLightningComponent")
	}
	static class UTempestLightningComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTempestLightningComponent>();
	}
};
DUMPER7_ASSERTS_UTempestLightningComponent;

// Class SuperstormRuntime.TempestTornadoForcesComponent
// 0x0470 (0x0520 - 0x00B0)
class UTempestTornadoForcesComponent final : public UGameFrameworkComponent
{
public:
	struct FDataTableRowHandle                    ConfigHandle;                                      // 0x00B0(0x0010)(Edit, DisableEditOnInstance, NoDestructor, Protected, NativeAccessSpecifierProtected)
	TArray<struct FGameplayTag>                   PhysicsPresetTagsAngularDampingToOverride;         // 0x00C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         AngularDampingOverride;                            // 0x00D0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	TSubclassOf<class UGameplayEffect>            PawnInGE;                                          // 0x00F8(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TMap<ETornadoObjectType, struct FScalableFloat> ObjectTypeToMaxCapCount;                         // 0x0100(0x0050)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	struct FGameplayTagContainer                  TagsToIgnore;                                      // 0x0150(0x0020)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	TSubclassOf<class UGameplayEffect>            RecentlyRemovedGE;                                 // 0x0170(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UTargetingPreset*                       TargetingPreset;                                   // 0x0178(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FGameplayTag                           DamageSetByCallerTag;                              // 0x0180(0x0008)(Edit, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TSubclassOf<class UGameplayEffect>            PeriodicDamageGE;                                  // 0x0188(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TSubclassOf<class UGameplayEffect>            BurstDamageGE;                                     // 0x0190(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FGameplayTag                           TornadoActiveCue;                                  // 0x0198(0x0008)(Edit, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FGameplayTag                           PlayerNearCue;                                     // 0x01A0(0x0008)(Edit, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FGameplayTag                           PawnInCue;                                         // 0x01A8(0x0008)(Edit, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FScalableFloat                         PlayerNearRange;                                   // 0x01B0(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FGameplayTagContainer                  BlockAbilitiesWithTag;                             // 0x01D8(0x0020)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FTornadoClientSimulationArray          ActorsToClientSimulate;                            // 0x01F8(0x0118)(Net, Transient, NativeAccessSpecifierPrivate)
	uint8                                         Pad_310[0x110];                                    // 0x0310(0x0110)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTargetingRequestHandle                AsyncTargetingHandle;                              // 0x0420(0x0004)(Transient, NoDestructor, NativeAccessSpecifierPrivate)
	uint8                                         Pad_424[0x4];                                      // 0x0424(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSet<class AFortPlayerPawn*>                  PreviouslyNearPlayers;                             // 0x0428(0x0050)(Transient, NativeAccessSpecifierPrivate)
	uint8                                         Pad_478[0xA8];                                     // 0x0478(0x00A8)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	bool IsActorInTornado(class AActor* Actor) const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TempestTornadoForcesComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TempestTornadoForcesComponent")
	}
	static class UTempestTornadoForcesComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTempestTornadoForcesComponent>();
	}
};
DUMPER7_ASSERTS_UTempestTornadoForcesComponent;

// Class SuperstormRuntime.TornadoRadialForce
// 0x0038 (0x0260 - 0x0228)
class ATornadoRadialForce final : public AFieldSystemActor
{
public:
	float                                         Radius;                                            // 0x0228(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Strength;                                          // 0x022C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StartTime;                                         // 0x0230(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StopTime;                                          // 0x0234(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         IncomingDuration;                                  // 0x0238(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OutgoingDuration;                                  // 0x023C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_240[0x8];                                      // 0x0240(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class URadialVector*                          RadialVector;                                      // 0x0248(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class URadialFalloff*                         RadialFalloff;                                     // 0x0250(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UOperatorField*                         OperatorField;                                     // 0x0258(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TornadoRadialForce")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TornadoRadialForce")
	}
	static class ATornadoRadialForce* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATornadoRadialForce>();
	}
};
DUMPER7_ASSERTS_ATornadoRadialForce;

}

