#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VKEditUI

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// Class VKEditUI.VKConnectionIndicator
// 0x0008 (0x02B8 - 0x02B0)
class UVKConnectionIndicator final : public UFortHUDElementWidget
{
public:
	bool                                          bHasActiveConnection;                              // 0x02B0(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2B1[0x7];                                      // 0x02B1(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void BP_OnConnectionChanged();
	void OnConnectionToEditChanged(bool bConnected);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("VKConnectionIndicator")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VKConnectionIndicator")
	}
	static class UVKConnectionIndicator* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVKConnectionIndicator>();
	}
};
DUMPER7_ASSERTS_UVKConnectionIndicator;

// Class VKEditUI.VKDebugMessagesBase
// 0x0000 (0x02B0 - 0x02B0)
class UVKDebugMessagesBase final : public UFortHUDElementWidget
{
public:
	void BP_OnGameStateInitialized(class AFortGameState* GameState);
	void HandleGameStateInitialized(class AFortGameState* GameState);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("VKDebugMessagesBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VKDebugMessagesBase")
	}
	static class UVKDebugMessagesBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVKDebugMessagesBase>();
	}
};
DUMPER7_ASSERTS_UVKDebugMessagesBase;

}

